### ISSUE TITLE
rendering for args option

### ISSUE THREAD

**Issue by nathraQ** [mariusschulz/gulp-iife#5]
I tried to use the *args* option. It just adds ```(function(){ ...})(arg1, arg2);``` I expected ```(function(arg1, arg2){ ...})(arg1, arg2);```.

The second issue is that I have to declare global variables first ( to use window, document or undefined I have to write the following first ```var window = window```)m before I can use them in the args array

**Comment by mariusschulz** [comment]
Up to version 0.1.0, the `args` option behaved exactly as you observed. A solution would've been to use the `params` options to which `args` falls back to if `args` is not explicitly specified.

However, you're right, this dichotomy is confusing, which is why I've gotten rid of it (see https://github.com/mariusschulz/gulp-iife/commit/d28e4f73bad8c0166b8a1733dd91f42185ca75d9). Your above code should now work as is.

Could you elaborate on the second part of the issue? I'm not sure I follow.

**Comment by nathraQ** [comment]
Thanks for the quick solution. As I mentioned in the commit the second part can be answered as one should use strings naming the variable. Maybe add this information to the readme file

**Comment by mariusschulz** [comment]
I've updated [README.md](https://github.com/mariusschulz/gulp-iife/blob/master/README.md) to include an example of how to use `params` and `args`.

**Comment by nathraQ** [comment]
thanks for the great work :+1:
